### ISSUE TITLE
Peripherals for custom board

### ISSUE THREAD

**Issue by Barmallini** [OpenNuvoton/MA35D1_Buildroot#18]
Hi,
how to add peripheral to custom board?

Maybe somewhere custom .dtsi ?

I'm use buildroot image from Nuvoton (Virtualbox)

**Comment by ychuang3** [comment]
First, please update Buildroot:
```
git pull
```
Then, perform a clean build and select the appropriate board configuration:

```
rm -rf output
make numaker_som_ma35d16a81_defconfig  # Assuming your board is SOM 256MB
make
```
The build process will take about an hour or more to complete.
After that, you can customize your .dtsi file. It can be found at:
```
buildroot/output/build/linux-custom/arch/arm64/boot/dts/nuvoton/ma35d1.dtsi
```

**Comment by Barmallini** [comment]
What about i2c0 ?
No PMIC at board...

![i2c0](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/11353228/5c9424bf-3e25-4c22-b1b6-91cc50aa0e52)

**Comment by ychuang3** [comment]
It depends on what device is connected to the I2C0 on your board.

**Comment by Barmallini** [comment]
Fram and temperature sensor, nothing special

We are found right interrupt for i2c0 and add it to dtsi.
I hope it's the same as i2c1 from hardware point of view

**Comment by ychuang3** [comment]
I2C0 reset default is TZS (Trust Zone Secure) which cannot be accessed by Linux.
You have to add <I2C0_TZNS> to the sspcc node of "buildroot/output/build/arm-trusted-firmware-custom/fdts/ma35d1.dtsi".
```
	sspcc: sspcc@404F0000 {
		compatible = "nuvoton,ma35d1-sspcc";
		reg = <0x0 0x404F0000 0x0 0x1000>;
		config = <UART0_TZNS>,
			<I2C0_TZNS>,
			<SDH0_TZNS>,
```

Find your dts (generaly be ma35d1-cpu800-custom-ddr.dts) and remove the following setting, which will set I2C0 pins as secure and prevent form accessed by Linux.
```
&sspcc {
	gpio_s = <PD6_S>,
		<PD7_S>;
};
```

Because you do not use PMIC, please disable PMIC by buildroot menuconfig:
```
Bootloaders  ---> 
     MA35D1 PMIC Select (No PMIC) 
```
Hope this can work for you.

**Comment by Barmallini** [comment]
Tell me please interrupt number for i2c0

**Comment by Barmallini** [comment]
Worked, interrupt 13
Must rebuild trustzone after adding i2c
